# Generated by Django 2.2 on 2019-04-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190415_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayed',
            name='bad_gestures',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameplayed',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Doctor'),
        ),
    ]
