# Generated by Django 2.2 on 2019-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190418_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_notes',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(default='empty'),
        ),
    ]
