# Generated by Django 2.1.7 on 2019-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesture',
            name='decision_tree',
            field=models.TextField(),
        ),
    ]
